name: Apicurio Registry Operator - Build and test a pull request

on: [ pull_request ]

env:
  IMAGE_REGISTRY: quay.io

jobs:
  test:
    name: Build and test a pull request
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version

      - name: Setup the environment
        run: .github/scripts/setup.sh

      - name: Build
        run: make build bundle bundle-build

      - name: Test
        run: CI_BUILD=true .github/scripts/test_operator.sh

      - name: Collect logs
        if: failure()
        run: .github/scripts/collect_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-logs
          path: artifacts
