name: Apicurio Registry Operator - Build and publish from main
on:
  push:
    branches:
      - main

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_REGISTRY_ORG: apicurio

jobs:
  main:
    name: Build and publish from main
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.8'
      - run: go version

      - name: Setup the environment
        run: ./.github/scripts/setup.sh

      - name: Setup Docker
        run: |
          docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" "${IMAGE_REGISTRY}"

      - name: Build
        id: build
        run: make all

      - name: Publish
        id: publish
        run: make all-push

      - name: Test
        id: test
        run: ./.github/scripts/test_operator.sh

      - name: Collect logs
        if: failure()
        run: ./.github/scripts/collect_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: tests-logs
          path: artifacts
