name: Apicurio Registry Operator - Build and publish from main
on:
  push:
    branches:
      - main

env:
  IMAGE_REGISTRY: quay.io

# TODO Regenerate install/install.yaml file
jobs:
  main:
    name: Build and publish from main
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version

      - name: Setup the environment
        run: .github/scripts/setup.sh

      - name: Setup Docker
        run: |
          docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" "${IMAGE_REGISTRY}"

      - name: Build
        run: make build bundle bundle-build dist

      - name: Test Before
        run: CI_BUILD=true .github/scripts/test_operator.sh

      - name: Publish
        run: make docker-push bundle-push catalog-build catalog-push

      - name: Test After
        run: .github/scripts/test_operator.sh

      - name: Collect logs
        if: failure()
        run: .github/scripts/collect_logs.sh

      - name: Upload tests logs artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-logs
          path: artifacts
